import type { NarrativeRule } from './types';

export const NARRATIVE_RULES: NarrativeRule[] = [
  {
    id: 'exit.concentration.extreme.01',
    category: 'concentration',
    priority: 90,
    severity: 'critical',
    conditions: [{ field: 'concentrationExtreme', operator: 'eq', value: true }],
    template:
      'This shows that approximately {businessValueShareOfNetWorth} of total net worth is concentrated in the business stake — an extreme concentration position based on the assumptions entered.',
    variables: ['businessValueShareOfNetWorth'],
    disclaimerTags: ['assumptions', 'risk-warning'],
    displayOrder: 10,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'exit.concentration.high.01',
    category: 'concentration',
    priority: 80,
    severity: 'warning',
    conditions: [{ field: 'concentrationHigh', operator: 'eq', value: true }],
    template:
      'This shows that approximately {businessValueShareOfNetWorth} of total net worth is concentrated in the business stake, based on the assumptions entered.',
    variables: ['businessValueShareOfNetWorth'],
    disclaimerTags: ['assumptions'],
    displayOrder: 20,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'exit.concentration.high.02',
    category: 'concentration',
    priority: 75,
    severity: 'warning',
    conditions: [{ field: 'concentrationHigh', operator: 'eq', value: true }],
    template:
      'This reflects a high concentration position, with about {businessValueShareOfNetWorth} of personal net worth linked to the exit value.',
    variables: ['businessValueShareOfNetWorth'],
    disclaimerTags: ['risk-warning'],
    displayOrder: 21,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'exit.concentration.moderate.01',
    category: 'concentration',
    priority: 60,
    severity: 'info',
    conditions: [
      { field: 'concentrationModerate', operator: 'eq', value: true },
      { field: 'concentrationHigh', operator: 'eq', value: false },
    ],
    template:
      'This shows a moderate concentration position, with approximately {businessValueShareOfNetWorth} of net worth linked to the business stake in this snapshot model.',
    variables: ['businessValueShareOfNetWorth'],
    disclaimerTags: ['assumptions'],
    displayOrder: 30,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'badr.eligible.01',
    category: 'badr',
    priority: 85,
    severity: 'info',
    conditions: [{ field: 'badrEligible', operator: 'eq', value: true }],
    template:
      'This shows that the current inputs meet the stated BADR holding-period and ownership tests, subject to the assumptions entered.',
    variables: ['holdingPeriodYears', 'ownershipPercent', 'badrEligible'],
    disclaimerTags: ['tax-assumptions'],
    displayOrder: 40,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'badr.noteligible.01',
    category: 'badr',
    priority: 85,
    severity: 'warning',
    conditions: [{ field: 'badrEligible', operator: 'eq', value: false }],
    template:
      'This shows that the disposal does not currently meet the stated BADR holding-period or ownership tests.',
    variables: ['holdingPeriodYears', 'ownershipPercent', 'badrEligible'],
    disclaimerTags: ['tax-assumptions'],
    displayOrder: 41,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'badr.headroom.exceeded.01',
    category: 'badr',
    priority: 80,
    severity: 'warning',
    conditions: [{ field: 'badrHeadroomExceeded', operator: 'eq', value: true }],
    template:
      'This shows that the capital gain of {gainsAfterLosses} exceeds remaining BADR lifetime headroom of {badrHeadroomRemaining}.',
    variables: ['gainsAfterLosses', 'badrHeadroomRemaining'],
    disclaimerTags: ['tax-assumptions'],
    displayOrder: 42,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'cgt.splitrate.01',
    category: 'cgt',
    priority: 70,
    severity: 'info',
    conditions: [
      { field: 'badrEligible', operator: 'eq', value: true },
      { field: 'hasCapitalLoss', operator: 'eq', value: false },
      { field: 'nonBadrGain', operator: 'gt', value: 0 },
    ],
    template:
      'This shows that the non-BADR gain is split between the basic and higher rate bands, with {basicRatePortion} at 18% and {higherRatePortion} at 24%.',
    variables: ['basicRatePortion', 'higherRatePortion', 'nonBadrGainTax'],
    disclaimerTags: ['tax-assumptions'],
    displayOrder: 50,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'gain.zero.loss.01',
    category: 'cgt',
    priority: 75,
    severity: 'info',
    conditions: [{ field: 'hasCapitalLoss', operator: 'eq', value: true }],
    template:
      'This shows a zero or negative capital gain position, with a calculated gain of {grossCapitalGain}.',
    variables: ['grossCapitalGain'],
    disclaimerTags: ['limitations'],
    displayOrder: 51,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'tax.effective.high.01',
    category: 'tax',
    priority: 70,
    severity: 'warning',
    conditions: [{ field: 'effectiveTaxHigh', operator: 'eq', value: true }],
    template:
      'This shows an effective exit tax rate of {effectiveTaxRate}, which is above 20% on the current assumptions.',
    variables: ['effectiveTaxRate'],
    disclaimerTags: ['tax-assumptions'],
    displayOrder: 60,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'inputs.multiple.assumptions',
    category: 'assumptions',
    priority: 50,
    severity: 'info',
    conditions: [{ field: 'assumptionCount', operator: 'gte', value: 2 }],
    template:
      'This calculation uses multiple assumptions, so the output should be treated as an indicative estimate only.',
    variables: ['assumptionCount'],
    disclaimerTags: ['assumptions', 'limitations'],
    displayOrder: 70,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'planning.concentration.01',
    category: 'planning',
    priority: 40,
    severity: 'info',
    conditions: [{ field: 'concentrationHigh', operator: 'eq', value: true }],
    template:
      'Topics to explore with a qualified adviser: diversification strategies, staged exit options, and wealth concentration management.',
    variables: [],
    disclaimerTags: ['planning-topic'],
    displayOrder: 80,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'planning.badr.01',
    category: 'planning',
    priority: 40,
    severity: 'info',
    conditions: [{ field: 'badrEligible', operator: 'eq', value: false }],
    template:
      'Topics to explore with a qualified adviser: BADR eligibility conditions, holding period planning, and alternative CGT reliefs.',
    variables: [],
    disclaimerTags: ['planning-topic'],
    displayOrder: 81,
    jurisdiction: 'UK',
    appliesWhen: 'clientFacing',
    version: '1.0',
    effectiveFrom: '2026-01-01',
  },
];

export const DISCLAIMER_MODULES: Record<string, string> = {
  assumptions:
    'Based on the assumptions entered; not a guarantee of outcome. Individual circumstances may differ.',
  'not-advice':
    'This is an illustration only and is not tax, legal, or investment advice.',
  'tax-assumptions':
    'Based on current law and rates at the calculation date. Individual tax treatment may differ.',
  'risk-warning':
    'Concentration and risk flags are model outputs based on the assumptions entered — not recommendations.',
  limitations:
    'This snapshot has scope boundaries. Incomplete or assumed inputs reduce reliability.',
  'planning-topic':
    'These topics are for discussion with a qualified adviser — not personalised advice.',
};
